image: "golang:1.13"

before_script:
  - git clone https://github.com/katzenpost/client
  - go build
  - cd client

test-client:
  script:
    - go test -v -cover -race -timeout 0 -ldflags "-X github.com/katzenpost/core/epochtime.WarpedEpoch=true -X github.com/katzenpost/server/internal/pki.WarpedEpoch=true" ./...
