image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - git clone https://github.com/katzenpost/server.git; cd server
    - docker build -t katzenpost/server .; cd ..
    - git clone https://github.com/katzenpost/authority.git; cd authority
    - docker build -t katzenpost/authority .; cd ..
    - git clone https://github.com/katzenpost/docker.git; cd docker
    - docker-compose start
    - sleep 10
    - docker-compose stop