image: "golang:1.12"

variables:
  GO111MODULE: "on"

test-client:
  script:
   - apt install docker docker-compose
   - git clone https://github.com/katzenpost/docker.git
   - cd docker
   - docker-compose start
