
[[Account]]
  name = "Alice"
  provider = "Acme.com"

[[Account]]
  name = "Carol"
  provider = "ProviderOfNet"

[[Account]]
  name = "Eve"
  provider = "Trustworthy"

#[[ProviderPinning]]
#  certificate = "/blah/blah/certs/acme.pem"
#  name = "Acme"

[SMTPProxy]
  Address = "127.0.0.1:2525"
  Network = "tcp"
