
[[Account]]
  name = "Alice"
  provider = "Acme"

[[Account]]
  name = "Carol"
  provider = "ProviderOfNet"

[[Account]]
  name = "Eve"
  provider = "Trustworthy"

# always use this certificate with Acme
# regardless of what the PKI says to use
[[ProviderPinning]]
  name = "Acme"
  certificate = "/blah/blah/certs/acme.pem"
